# Generated by Django 3.1.4 on 2020-12-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20201224_2038'),
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='image',
            field=models.ImageField(null=True, upload_to='cast/'),
        ),
        migrations.AlterField(
            model_name='cast',
            name='films',
            field=models.ManyToManyField(related_name='casts', to='films.Film'),
        ),
        migrations.CreateModel(
            name='TVActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Actor's name")),
                ('age', models.PositiveSmallIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other...')], max_length=40)),
                ('image', models.ImageField(null=True, upload_to='tvactor/')),
                ('shows', models.ManyToManyField(to='films.TVShow')),
            ],
        ),
    ]
