# Generated by Django 3.1.4 on 2020-12-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_auto_20201224_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='show',
            field=models.ForeignKey(default='sdfg', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='films.tvshow'),
            preserve_default=False,
        ),
    ]
